name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      commit:
        description: "Git commit, branch, or tag to deploy"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Build backend Docker image
        run: docker build -t webapp-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t webapp-frontend ./frontend

  deploy:
    needs: build
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    if: github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Deploy selected version
        run: |
          cd ~/webapp
          ./deploy.sh "${{ inputs.commit}}"
